name: New Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Say Hello
        run: echo "Hello, world!"

      - name: Send approval request email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: 'Action needed: Approve deployment'
          to: ${{ secrets.APPROVER_EMAIL }}
          from: github-actions@example.com
          body: |
            Hello,

            Please approve the deployment by reviewing and approving the GitHub Actions job 
            in the 'production' environment at:

            https://github.com/${{ github.repository }}/actions

            Thanks!
            
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Deployment after approval
        run: echo "Deployment approved and running..."
